/*****************************************************************************
* Model: comp.qm
* File:  ./src/alarm.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#ifndef alarm_h
#define alarm_h
#include "qp_port.h"
#include "qmbsp.h"

#define Alarm_init(me_)           QHsm_init    ((QHsm *)(me_), (QEvent *)0)

/* @(/2/0) .................................................................*/
typedef struct AlarmTag {
/* protected: */
    QHsm super;

/* private: */
    Time time;
} Alarm;

/* public: */
void Alarm_ctor(Alarm * const me);

/* protected: */
QState Alarm_initial(Alarm * const me, QEvt const * const e);
QState Alarm_off(Alarm * const me, QEvt const * const e);
QState Alarm_on(Alarm * const me, QEvt const * const e);


void Alarm_ctor(Alarm * const me);


#endif /* alarm_h */
